name: Build Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: git.automatizase.com.br
  REGISTRY_PATH: luis.erlacher/archon

jobs:
  build-server:
    runs-on: wsl
    steps:
      - name: Checkout
        run: |
          git clone https://git.automatizase.com.br/luis.erlacher/Archon.git .
          git checkout ${{ github.sha }}

      - name: Build and push server
        run: |
          cd python
          docker build -f Dockerfile.server -t ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/server:latest .
          docker push ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/server:latest

  build-mcp:
    runs-on: wsl
    steps:
      - name: Checkout
        run: |
          git clone https://git.automatizase.com.br/luis.erlacher/Archon.git .
          git checkout ${{ github.sha }}

      - name: Build and push mcp
        run: |
          cd python
          docker build -f Dockerfile.mcp -t ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/mcp:latest .
          docker push ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/mcp:latest

  build-frontend:
    runs-on: wsl
    steps:
      - name: Checkout
        run: |
          git clone https://git.automatizase.com.br/luis.erlacher/Archon.git .
          git checkout ${{ github.sha }}

      - name: Build and push frontend
        run: |
          cd archon-ui-main
          docker build -f Dockerfile -t ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/frontend:latest .
          docker push ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/frontend:latest

  build-agents:
    runs-on: wsl
    steps:
      - name: Checkout
        run: |
          git clone https://git.automatizase.com.br/luis.erlacher/Archon.git .
          git checkout ${{ github.sha }}

      - name: Build and push agents
        run: |
          cd python
          docker build -f Dockerfile.agents -t ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/agents:latest .
          docker push ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/agents:latest
