name: Test Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: wsl

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build archon-server image
        run: |
          cd python
          docker build -f Dockerfile.server -t archon-server:test .

      - name: Show Docker images
        run: docker images | grep archon
